name: Publish documentation to GH Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user pipx
        pipx install poetry
        pipx install mkdocstrings-python --include-deps

    - name: Build & Publish
      run: |
        mkdocs gh-deploy --no-history
