name: Publish Python Module to PyPI

on: 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user pipx
        pipx install poetry

    - name: Build & Test
      run: |
        poetry install
        poetry run pytest

    - name: Patch version
      if: ${{ vars.PATCH_POETRY_VERSION == 'true' }}
      run: poetry version patch

    - name: Publish package
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
 #       poetry publish --build --no-interaction

    - name: Push updated version
      if: ${{ vars.PATCH_POETRY_VERSION == 'true' }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -a -m "Update library version"
        git push